### ISSUE TITLE
documentation api

### ISSUE THREAD

**Issue by stabylo** [azerpas/carrefour-drive-monitor#1]
Joli travail et très utile par les temps qui courent.
Dis moi, je n'arrive pas à mettre la main sur la documentation de leur api, tu sais où elle se cache ?

**Comment by azerpas** [comment]
Hello, honnêtement aucune idée, j'ai simplement récupéré les différents endpoints utilisés sur leur version web. Je ne pourrais malheureusement pas t'aider...
