### ISSUE TITLE
Is it still working ?

### ISSUE THREAD

**Issue by z0ph** [azerpas/carrefour-drive-monitor#2]
Hi @azerpas ,

Pour le coup, azer bien 👍🏼 

Ce programme fonctionne toujours ? Je voudrai récupérer les slots disponible dans l'un des drives proche de chez moi.

```
    pr = random.choice(proxies)[0]
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

Le proxy sert à quoi ? est-il obligatoire ?

**Comment by azerpas** [comment]
Hello ! 

Malheureusement je n'ai pas maintenu le programme par manque de temps, mais j'imagine qu'il doit toujours être possible d'en faire quelque chose.

Le proxy sert à cacher ton ip et éventuellement éviter de te faire ban par Carrefour (et surtout Datadome) dû au gros nombre de requêtes qui sont faites. Il est de ce fait obligatoire. 😕

**Comment by z0ph** [comment]
Je pense qu'il y a un truc a faire entre ces deux initiatives :)

- https://github.com/nlevee/go-carrefour-drive-checker

**Comment by azerpas** [comment]
Je suis pas sûr d'avoir le temps de mettre à jour ce projet mais pas de soucis pour expliquer mon usage de proxies. 😁
